# 03 — Handling Class Imbalance & Model Selection
### Lending Club Accepted Loans — Credit Risk (Default Prediction)

1. **Calibrate expectations** — how imbalanced is this problem, really, and what does
   that imply about which techniques are worth trying at all.
2. **Bake-off** — compare the standard imbalance-handling techniques on equal footing,
   with the metrics that actually matter under imbalance (not accuracy).
3. **The trade-off that matters most in credit risk** — resampling changes what your
   predicted probabilities *mean*, which is a problem the moment you need real
   probabilities (expected loss, pricing, reserving) rather than just a rank-ordering.
4. **Model zoo + tuning** — once the imbalance strategy is settled, compare model
   families and tune the best one, using a CV scheme that respects the time structure
   established in notebook 02.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

train_df = pd.read_csv('train.csv')
val_df = pd.read_csv('val.csv')
test_df = pd.read_csv('test.csv')

TARGET = 'bad_flag'
feature_cols = [c for c in train_df.columns if c != TARGET]

X_train, y_train = train_df[feature_cols], train_df[TARGET]
X_val, y_val = val_df[feature_cols], val_df[TARGET]
X_test, y_test = test_df[feature_cols], test_df[TARGET]

print(f"train={len(X_train):,}  val={len(X_val):,}  test={len(X_test):,}")
print(f"bad rate — train={y_train.mean():.3f} val={y_val.mean():.3f} test={y_test.mean():.3f}")

train=492,256  val=92,633  test=88,733
bad rate — train=0.148 val=0.147 test=0.149

## 1. Calibrating expectations

A ~20-35% bad rate (depending on your exact filtering) is **mild-to-moderate**
imbalance — nowhere near fraud (often <1%) or rare-disease screening (often <1%). The realistic contenders, roughly in the order you should reach for them:

1. **Class weighting** (`class_weight='balanced'` / `scale_pos_weight`) — reweights the
   loss function, changes no actual data. Cheap, reversible, doesn't touch your
   feature distributions.
2. **Threshold moving** — train normally, choose a decision threshold that reflects the
   real cost asymmetry (covered fully in notebook 04). Often does more for you than any
   resampling technique, because it directly targets what you actually control at
   inference time: the accept/decline cutoff.
3. **Under/oversampling (SMOTE etc.)** — changes the training data itself. Useful when
   the model genuinely can't learn the minority class's *pattern* with weighting alone
   — less common at this level of imbalance, but worth testing rather than assuming.

## 2. A shared preprocessing pipeline for the bake-off

Every technique below needs the same encoding: `TargetEncoder` for the categoricals
(fit only on the training fold — sklearn's implementation cross-fits internally, which
is what prevents it from leaking), `StandardScaler` for everything else. Building this
once as a `ColumnTransformer` keeps the comparison fair — every configuration sees
identical features, and the *only* thing that changes is the imbalance treatment.

In [2]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import TargetEncoder, StandardScaler

cat_cols = X_train.select_dtypes(include='object').columns.tolist()
num_cols = [c for c in feature_cols if c not in cat_cols]
print(f"{len(cat_cols)} categorical, {len(num_cols)} numeric features")

preprocess = ColumnTransformer([
    ('cat', TargetEncoder(target_type='binary', random_state=42), cat_cols),
    ('num', StandardScaler(), num_cols),
])

X_train_enc = preprocess.fit_transform(X_train, y_train)
X_val_enc = preprocess.transform(X_val)
X_test_enc = preprocess.transform(X_test)

11 categorical, 90 numeric features

## 3. The bake-off

We hold the classifier fixed (logistic regression — fast, and its probability outputs
make the calibration-distortion point in the next section easy to see) and vary only
the imbalance treatment. **ROC-AUC and PR-AUC together, not accuracy**: ROC-AUC can look
deceptively stable under imbalance because it's evaluated against both classes
symmetrically, while PR-AUC is sensitive to exactly the thing we care about — how well
the model finds the minority (bad) class without drowning in false positives. The
no-skill PR-AUC baseline equals the bad rate itself (~0.2-0.35 here) — a model has to
beat *that*, not zero, to be adding value.

In [6]:
# ! pip install imblearn

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, average_precision_score, f1_score
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

def evaluate(model, X, y):
    p = model.predict_proba(X)[:, 1]
    pred = (p >= 0.5).astype(int)
    return {
        'roc_auc': roc_auc_score(y, p),
        'pr_auc': average_precision_score(y, p),
        'f1_at_0.5': f1_score(y, pred),
    }

bakeoff_results = {}

# (a) baseline — no handling at all
m = LogisticRegression(max_iter=1000).fit(X_train_enc, y_train)
bakeoff_results['no_handling'] = evaluate(m, X_val_enc, y_val)

# (b) class weighting
m = LogisticRegression(max_iter=1000, class_weight='balanced').fit(X_train_enc, y_train)
bakeoff_results['class_weight'] = evaluate(m, X_val_enc, y_val)

# (c) random undersampling
rus = RandomUnderSampler(random_state=42)
X_rus, y_rus = rus.fit_resample(X_train_enc, y_train)
m = LogisticRegression(max_iter=1000).fit(X_rus, y_rus)
bakeoff_results['undersample'] = evaluate(m, X_val_enc, y_val)

# (d) SMOTE oversampling
sm = SMOTE(random_state=42)
X_sm, y_sm = sm.fit_resample(X_train_enc, y_train)
m = LogisticRegression(max_iter=1000).fit(X_sm, y_sm)
bakeoff_results['smote'] = evaluate(m, X_val_enc, y_val)

pd.DataFrame(bakeoff_results).T.round(4)

              roc_auc  pr_auc  f1_at_0.5
no_handling    0.7018  0.2763     0.0160
class_weight   0.7031  0.2746     0.3532
undersample    0.7025  0.2743     0.3522
smote          0.6975  0.2686     0.3506

At this level of imbalance, don't be surprised if the four rows land close together —
that's the expected result, not a bug in the experiment. It's itself the finding: with
only moderate imbalance, sophisticated resampling usually buys little-to-nothing over
simple class weighting, while (as the next section shows) it isn't free — it costs you
calibrated probabilities.

## 4. Why this matters beyond the metric: calibration distortion

`class_weight`/`scale_pos_weight` and resampling both push the model to behave as if
the bad rate were higher than it really is. That's exactly what you want for
*rank-ordering* (separating good from bad), but it also means the model's raw
`predict_proba` output is no longer an honest estimate of "the actual probability this
loan defaults" — it's inflated toward 50/50. If you only ever threshold the score, this
doesn't matter. It matters a great deal the moment you want to say "this loan has an
8% chance of default" for expected-loss math, pricing, or loss reserving. Notebook 04
puts real numbers on this and fixes it with `CalibratedClassifierCV`.

In [7]:
m_weighted = LogisticRegression(max_iter=1000, class_weight='balanced').fit(X_train_enc, y_train)
m_plain = LogisticRegression(max_iter=1000).fit(X_train_enc, y_train)

print('Mean predicted P(bad), plain model   :', m_plain.predict_proba(X_val_enc)[:,1].mean())
print('Mean predicted P(bad), weighted model:', m_weighted.predict_proba(X_val_enc)[:,1].mean())
print('Actual bad rate in validation set    :', y_val.mean())

Mean predicted P(bad), plain model   : 0.13960567551498435
Mean predicted P(bad), weighted model: 0.4426772280405062
Actual bad rate in validation set    : 0.14740967041982878

The weighted model's *average* predicted probability drifts away from the true bad
rate; the unweighted model's stays close to it (small deviation is normal sampling
noise, not perfect calibration — we check that properly with a reliability diagram in
notebook 04). This is the concrete version of the trade-off above.

## 5. Model zoo

With the imbalance strategy settled (`scale_pos_weight`/`class_weight`, revisited
properly via calibration downstream), we compare model families on the same
preprocessed features: logistic regression as the interpretable baseline, then
tree-based models that can capture non-linearities and interactions the linear model
can't.

In [8]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
model_zoo = {
    'logistic_regression': LogisticRegression(
        max_iter=1000, class_weight='balanced', C=0.1
    ),
    'random_forest': RandomForestClassifier(
        n_estimators=300, max_depth=8, min_samples_leaf=50,
        class_weight='balanced', n_jobs=-1, random_state=42
    ),
    'xgboost': XGBClassifier(
        n_estimators=300, max_depth=4, learning_rate=0.05,
        scale_pos_weight=pos_weight, eval_metric='logloss',
        tree_method='hist', random_state=42
    ),
    'lightgbm': LGBMClassifier(
        n_estimators=300, max_depth=4, learning_rate=0.05,
        class_weight='balanced', random_state=42, verbosity=-1
    ),
}

zoo_results = {}
for name, model in model_zoo.items():
    model.fit(X_train_enc, y_train)
    zoo_results[name] = evaluate(model, X_val_enc, y_val)

pd.DataFrame(zoo_results).T.round(4).sort_values('pr_auc', ascending=False)

                     roc_auc  pr_auc  f1_at_0.5
lightgbm              0.7108  0.2892     0.3572
xgboost               0.7107  0.2891     0.3576
logistic_regression   0.7027  0.2770     0.3526
random_forest         0.7012  0.2732     0.3538

Gradient boosting (XGBoost/LightGBM) typically edges out the rest on tabular credit
data like this — enough to justify the added complexity over logistic regression, but
usually not by a dramatic margin. That gap (or lack of one) is worth reporting
honestly: if logistic regression gets you 90% of the way to XGBoost's performance, that
model may be the right operational choice at a shop that also needs the near-total
transparency of a linear model.

## 6. Hyperparameter tuning with a time-aware CV scheme

Ourtraining set itself spans several years (notebook 02), so a *random* stratified fold
can let a tuning trial validate on data time-adjacent to its own training rows,
slightly overstating how well a parameter set will generalize forward in time. Swapping
in `TimeSeriesSplit` (expanding-window folds, always validating on the chronologically
later slice) mirrors the OOT discipline from notebook 02 inside the tuning loop itself.

In [11]:
# ! pip install optuna

In [12]:
import optuna
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import log_loss

optuna.logging.set_verbosity(optuna.logging.WARNING)

# Re-sort the *training* fold chronologically so TimeSeriesSplit's expanding windows
# are meaningful (train_df was already time-sorted in notebook 02, but this is cheap
# insurance if this notebook is ever run standalone against a re-shuffled train.csv).
train_sorted_idx = train_df['issue_d'].sort_values().index if 'issue_d' in train_df else train_df.index
tscv = TimeSeriesSplit(n_splits=4)

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 6),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.15, log=True),
        'min_child_weight': trial.suggest_int('min_child_weight', 5, 200),
        'subsample': trial.suggest_float('subsample', 0.7, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 1.0),
    }
    fold_losses = []
    X_arr = np.asarray(X_train_enc)
    y_arr = y_train.values
    for tr_idx, va_idx in tscv.split(X_arr):
        model = XGBClassifier(
            n_estimators=1000, early_stopping_rounds=30,
            scale_pos_weight=pos_weight, eval_metric='logloss',
            tree_method='hist', random_state=42, verbosity=0, **params,
        )
        model.fit(X_arr[tr_idx], y_arr[tr_idx],
                  eval_set=[(X_arr[va_idx], y_arr[va_idx])], verbose=False)
        p = model.predict_proba(X_arr[va_idx])[:, 1]
        fold_losses.append(log_loss(y_arr[va_idx], p))
    return float(np.mean(fold_losses))

study = optuna.create_study(direction='minimize', study_name='xgb_credit_risk')
study.optimize(objective, n_trials=25, show_progress_bar=False)

print('Best log-loss:', study.best_value)
print('Best params:', study.best_params)

Best log-loss: 0.5144449452035382
Best params: {'max_depth': 6, 'learning_rate': 0.08992893862967102, 'min_child_weight': 6, 'subsample': 0.9987083083715508, 'colsample_bytree': 0.9446428814861184}

**A runtime note for the real 1M+ row dataset:** a 4-fold time-series search over 25
trials means ~100 full model fits. On the full data that can get slow fast. In
practice, run the search on a stratified (and, ideally, time-stratified) subsample —
e.g. 15-20% of `train.csv` — then retrain the winning configuration on the full
training set. The Bayesian search is choosing *hyperparameters*, which are stable
across sample size well before the final model needs to be trained on everything.

In [13]:
final_model = XGBClassifier(
    n_estimators=800,
    scale_pos_weight=pos_weight,
    eval_metric='logloss',
    tree_method='hist',
    random_state=42,
    **study.best_params,
)
final_model.fit(X_train_enc, y_train)

print('Final model — validation metrics:')
print(evaluate(final_model, X_val_enc, y_val))
print('Final model — OOT test metrics:')
print(evaluate(final_model, X_test_enc, y_test))

Final model — validation metrics:
{'roc_auc': 0.70381224175829, 'pr_auc': 0.2810797014145044, 'f1_at_0.5': 0.35523922854127843}
Final model — OOT test metrics:
{'roc_auc': 0.7034532173324813, 'pr_auc': 0.28569065234745444, 'f1_at_0.5': 0.3545570489551653}

Compare validation vs. test here deliberately — a meaningful drop on the OOT test set
relative to validation is the population-drift signal notebook 02's split was designed
to surface. A small, consistent gap is normal; a large one means the model has
overfit to development-window patterns that don't hold up going forward.

In [14]:
import joblib

joblib.dump(preprocess, 'preprocess.joblib')
joblib.dump(final_model, 'xgb_raw_model.joblib')

comparison_table = pd.DataFrame({**bakeoff_results, **zoo_results}).T.round(4)
comparison_table.to_csv('model_comparison.csv')
comparison_table

                     roc_auc  pr_auc  f1_at_0.5
no_handling           0.7018  0.2763     0.0160
class_weight          0.7031  0.2746     0.3532
undersample           0.7025  0.2743     0.3522
smote                 0.6975  0.2686     0.3506
logistic_regression   0.7027  0.2770     0.3526
random_forest         0.7012  0.2732     0.3538
xgboost               0.7107  0.2891     0.3576
lightgbm              0.7108  0.2892     0.3572

## Summary

- At this dataset's imbalance level (~20-35% bad rate), class weighting matched or beat
  resampling on ranking metrics while leaving probabilities closer to honest — the
  right default here, not SMOTE-by-habit.
- Gradient boosting outperforms logistic regression, but the gap is worth quantifying
  and reporting rather than assumed.
- Hyperparameter tuning used `TimeSeriesSplit` internally, consistent with the
  out-of-time discipline from notebook 02 — with a note on subsampling for tuning
  speed at full data scale.
- Saved artifacts: `preprocess.joblib`, `xgb_raw_model.joblib` (uncalibrated),
  `model_comparison.csv`.

Next: **04 — full evaluation suite and probability calibration.**